travis:
  secure:
    BINSTAR_TOKEN: ZKSL2jFxYpwvBvFlKdfy7eh4lopV+522s/0FI0M0iYd2vFNWE5xgusR8BgJ5gcst1+p7n87TcJ8MBx/iTsomWPcKu4qk1P1/sI15lUqvLDBLZCdFhP0KzeNJsy1SmvqMmDcVefHlcIn7oit1DW55Y0rurlNDABo2FJ6nwfgY6imBjR1DuVKn75t4m54ZGwTn/H0+M2KBcDlCZ6IHlVqPfhlSEtbS9ikAsoI68wKM9PxCFDGlVI7qo8xedcmsGtYY6tPPoEnhNRvEp/P3SxowCG4SyZfChTmUahpY3phRczGNVvQCPsZjmlyktQK6c312V2CZplf5yeuAw8/F2oGhNz8rsNYdrP2fTTVYlTehH7umNnxc9KmBFbxJ49l0IR2pGbPdIjUKJkJ3nEFY3n1Lekx2Vbtc0ONHUE7aaJWtmVkbVPCugiOTPcIGcHDtYuWL4rrgVbEzYB1OXfU+lEKgCQHk30L8w5zMAAP0hddduahnc/JT/C+Whlz9tJFX9JVablgB5PTqZyhS6x5gYq70Bgb+WOtBoXUFvDquUGE+9DNPNN1OBiD/iHUQ6p7PeCYlOcNTEPw3qxZZCm03UvuoCkZOP9ucrhuvu8Gu9XJUQTRqOsIBy8MJp3I/9ew8mLLulzEYaru+fkY0U/fMD8Jbvf8gN/PKTBN3X0wfK6kVu7c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
