travis:
  secure:
    BINSTAR_TOKEN: pAJun9nTBNsjfH8DuO6NKlwEp2uLeX8EENX8N/ynmcWsqkdKlTAIHIVcTxAQ5a5znfokaHIR2aCK0VJ+Eg7+QHW2Wi8yGOsyvJf10PJdkbiBIj455AhQE8sUCIHiiFf+7DbLn6MRgH+xdARwIhIikMFHBiU/pDUWXlCYKgxjMplgCZfdNVKi9rLXjO/sIQup5IKoll2Fxsgb0jayc+HVlcKfeuAQJzEjfXvZl568/4i5WZPZzxMT82Fr8rHYtI9ko39KhOjHlHRJNb+dQxZPLOMyh0T58UncL91qJHOSdRXHbxuLyD07xqQaPBKNoTxgF26hmMTwFuvA6iAcw3mLcsdkO1DOLHeGihSId+duAuedFnsI2Eq2QJivcvTbCQTIKDiakrsMTQHmq7JWuW/d0pLCezPtqJfTVMxuhRFRbpbsYotAa1WJTlX7MUihAazJfrTIzIDvAs+Fghf1zpnohwgUV/nUHCQtk4tDzHrB6bxG/WQ5LpTpIycrWuoq7YjwhWQ9S6jdFJZhhn7J48WZrFPLQFO4ngvxWQW3IRcGZ8QJznXTazRSqTtOjDlqVpOjcgZEtSrgCI6jp+YHO//LJYQpUGMnlbegx1mAx1AABMXM6fd5yABEpTdiNJLwOhUT6ff5bnLUOPYjmUJT7y0etAjYTCK6QNQU2RBwMdv8kXo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
