travis:
  secure:
    BINSTAR_TOKEN: G5j4zYIYu8SV+WXwAfG5ZBku1HKfA30TH5p8NvsGozm9OYZYyHZDWOGWlFuDEgaD6zT+dv5fZaoyxIANq+X+33SvZCVEGi3YsEyx1rnat2MNaSRoLts+58qoMgbWRjoOFNmh/tBtsqmdjZV1qkgOreyjrAEr6NNFPdjx9NI+zCOhazLzGlszz+6IAL0DRXadURYJo4xciBqsYpIEOlQukA57+5J9qGIE1dScXFg8/FQm+ZZHMVhOoF8WfISkDHXwHV9R1r1hIzKx7fLudddX7pPBp8R93IdstK+Qa2D2eycEo/TrXcwTPacHvL345X2jOdxoxfPNjBwKSFWDnqa/g3+pRsYJQHszx40lvMBtftSe+ZPTcionx3y+KBQF2TjjkzR7LO1OYqelPFLc/fn4zp2a/Sf4ufCj9rpLWiKmMkNnAjt4kZvGY0Y9nM3H4vikrNe1Bh636qRgVO7bTghPmwyBnqXU4td8vZ62YNn4xSwrArQPon6EdfHqArbaL+ZfDpb19t839ffT+ulWh238KoJW4/8xwj0ChJ3h/+ZmsMgipbfUXUCKJgqpGipvE2G49Owl1SQXi4IzMDwByF+O6RTktuBe+4NjiulDa8VNX8DbaFQPciS8gNKfPfQt8cE9sg05WrX3SwsYEA/8r1yqtMyMIIh7acJFoQyRh+OOhjc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
