travis:
  secure:
    BINSTAR_TOKEN: bIwKSslIRE3KqrY4KoeWpGnQzPvgDrxvKpwupW6b+v9aedavKilkLVA4/rNjZN/DOooFKr7YrLLqHwwgCG/KDvQTE5dU3qdK8LetYAyyXywOXF1+g96dRxk0lNQOUB3Ez6pMPMYmXgPowhRRWHDqczWnvqILGt6dsSw20Df2y06xvACXOC2hP8QlDAp+efKkQ4WiXfAJDGdJuct/9Y+Ww6wY1kNpWKdXu+uC6K+EB3uq+BQNPzW1LqgEGyBQLaYm9Ya61jRH3guS9ccfti+kSQzBtrgDBIWJ/5ksa1So/6SABMZo+5U1aM/1SFTHN/1wHp+E5Rez3gQNcqJZdWK5VvXRsfNIYk6mYm71BnGbEbvduj8+fXBACc2VW2zOHGfBmSs5EGMMhArejKQ/zPl+uLCkMxBUq1b0wRGrLhfQN/bmcdNEGsqntqdypYOtOWgLpLBx7y9MXrVxmx2qvwkBRmA3JrBpij07gLWJyjJC8o5wECChpEzyxnzVS/AA2skCqoCNgSwVEVchnCTbjNk/RmbYcNPofPvU+yrs5ecMsS8VrPlNwaWaFkDobLPj8QafkgHv8OEVs7qQXNCJs+hARNGftfWa7jSTyyzq9H2PMgJSKG++MfO0CGu/TRGIsqJidB+5YzsOvsinEBCOEntUuxo1Xf0LlX24dU0vurXHLzM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
